### ISSUE TITLE
[테스트 데이터 생성기] CH 02. CLIP 05. 스프링 부트 프로젝트 초기화하기

### ISSUE THREAD

**Issue by incheol789** [incheol789/test-data#5]
한글 테스트 데이터 자동 생성기 서비스를 만들기 위한 소스코드 바탕 준비

## Todo
* [x] Spring Initializr: 자바 21 + 스프링 부트 3.3 으로 프로젝트 시작하기
* [x] 자바 21: 경고 로그 원인 찾고 제거하기
  * Class data sharing (CDS) 경고
  * Dynamic loading of agents 경고
* [x] 기초 application properties 셋업
* [ ] 미리 해둘 필요가 있는 기초 설정 코드 작성해두기
  * JPA
  * Security

## Reference
* https://docs.oracle.com/en/java/javase/21/vm/class-data-sharing.html
* https://stackoverflow.com/questions/77951485/getting-a-java-agent-has-been-loaded-warning-in-intellij-after-upgrading-jdk-17 
* https://belief-driven-design.com/looking-at-java-21-feature-deprecations-03fff/
* https://github.com/ryandens/javaagent-gradle-plugin
* https://docs.spring.io/spring-data/jpa/reference/auditing.html
* https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#jc-httpsecurity
* https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
